services:
  - type: web
    name: japan-working-holiday-app
    env: static
    buildCommand: npm install; npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
